

services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379
  
  front:
    container_name: react
    build: frontend/
    image: react:aamhamdi
    ports:
      - 5173:5173
    volumes:
      - /goinfre/aamhamdi/chatApp/frontend:/app
    working_dir: /app

  server:
    container_name: django
    build: backend/
    image: django:aamhamdi
    ports:
      - 8000:8000
    volumes:
      - /goinfre/aamhamdi/chatApp/backend:/app
    tty: true


