

services:
  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379
    restart : always
  
  front:
    container_name: react
    build: frontend/
    image: react:aamhamdi
    ports:
      - 5173:5173
    volumes:
      - ${PWD}/frontend:/app
    working_dir: /app
    restart: always

  server:
    container_name: django
    build: backend/
    image: django:aamhamdi
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/backend:/app
    tty: true
    restart : always


