# Generated by Django 4.2.14 on 2024-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_delete_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomid',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
