# Generated by Django 4.2.14 on 2024-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='roomid',
            field=models.CharField(max_length=500),
        ),
    ]
